version: "3.4"

networks:
  dev:
    driver: bridge

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    depends_on:
      - "digital_fuse"
    container_name: df-services
    ports:
      - "8443:443"
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ConnectionStrings__LiveDbString=Host=${DB_HOST};Database=${DB_DATABASE};Username=${DB_USERNAME};Password=${DB_PASSWORD}
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=8443
    networks:
      - dev

  digital_fuse:
    image: postgres:latest
    container_name: digital_fuse
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - digital_fuse:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  digital_fuse:
